### ISSUE TITLE
TypeError: Cannot read property 'onDestroy' of undefined

### ISSUE THREAD

**Issue by tanepiper** [ngneat/until-destroy#80] opened 2020-04-16 08:19 UTC
I'm currently writing a component where I want to have an internal subscription to a Reactive Form:

```
"@angular/animations": "^9.1.0",
"@angular/common": "^9.1.0",
"@angular/compiler": "^9.1.0",
"@angular/core": "^9.1.0",
"@angular/forms": "^9.1.0",
"@angular/platform-browser": "^9.1.0",
"@angular/platform-browser-dynamic": "^9.1.0",
"@angular/router": "^9.1.0",
"@ngneat/until-destroy": "^7.1.5",
```

```
import { Component, EventEmitter, forwardRef, OnInit, Output } from '@angular/core';
import { ControlValueAccessor, FormBuilder, NG_VALUE_ACCESSOR, Validators } from '@angular/forms';
import { tap } from 'rxjs/operators';
import { startWithTap } from '@shared/utils';
import { UntilDestroy, untilDestroyed } from '@ngneat/until-destroy';
import { combineLatest } from 'rxjs';

export interface CreditInvoiceDetails {
  date: string;
  user: string;
  reason: string;
}

@UntilDestroy()
@Component({
  selector: 'credit-invoice-details',
  templateUrl: './credit-invoice-details.component.html',
  styleUrls: ['./credit-invoice-details.component.css'],
  providers: [
    {
      provide: NG_VALUE_ACCESSOR,
      useExisting: forwardRef(() => CreditInvoiceDetailsComponent)
    }
  ]
})
export class CreditInvoiceDetailsComponent implements OnInit, ControlValueAccessor {
  @Output() detailsValid = new EventEmitter<boolean>();

  constructor(private readonly fb: FormBuilder) {}

  onChange: (details: CreditInvoiceDetails) => {};
  onTouch: () => {};

  public readonly detailsForm = this.fb.group({
    date: ['', [Validators.required]],
    user: ['', Validators.required],
    reason: ['', Validators.required]
  });

  ngOnInit(): void {
    combineLatest([this.detailsForm.statusChanges, this.detailsForm.valueChanges]).pipe(
      untilDestroyed(this),
      startWithTap(() => this.onTouch()),
      tap(([status, values]) => {
        this.detailsValid.emit(status !== 'INVALID')
        this.onChange(values)
      })
    ).subscribe()
  }

  /**
   * Register the change method
   * @param fn
   */
  registerOnChange(fn: any): void {
    this.onChange = fn;
  }

  /**
   * Register the touch method
   * @param fn
   */
  registerOnTouched(fn: any): void {
    this.onTouch = fn;
  }

  /**
   * Write the initial value to the form
   * @param obj
   */
  writeValue(obj: CreditInvoiceDetails): void {
    this.detailsForm.patchValue(obj);
  }

  /**
   * Set the disabled state of the form
   * @param isDisabled
   */
  setDisabledState(isDisabled: boolean): void {
    isDisabled ? this.detailsForm.disable() : this.detailsForm.enable();
  }
}
```

I have the following test:

```
import { async, ComponentFixture, TestBed } from '@angular/core/testing';

import { CreditInvoiceDetailsComponent } from './credit-invoice-details.component';
import { FormBuilder, ReactiveFormsModule } from '@angular/forms';
import { Component } from '@angular/core';

describe('CreditInvoiceDetailsComponent', () => {
  @Component({
    template: `
      <form [formGroup]="form">
        <credit-invoice-details formControlName="details" (detailsValid)="isValid = $event"></credit-invoice-details>
      </form>
    `
  })
  class CreditInvoiceDetailsSpecComponent {
    isValid = false;

    constructor(private readonly fb: FormBuilder) {}

    public readonly form = this.fb.group({
      details: [{ date: '', user: '', reason: '' }]
    });
  }

  let component: CreditInvoiceDetailsSpecComponent;
  let fixture: ComponentFixture<CreditInvoiceDetailsSpecComponent>;

  beforeEach(async(() => {
    TestBed.configureTestingModule({
      imports: [ReactiveFormsModule],
      declarations: [CreditInvoiceDetailsComponent, CreditInvoiceDetailsSpecComponent]
    }).compileComponents();
  }));

  beforeEach(() => {
    fixture = TestBed.createComponent(CreditInvoiceDetailsSpecComponent);
    component = fixture.componentInstance;
    fixture.detectChanges();
  });

  it('should create', () => {
    expect(component).toBeTruthy();
  });
});
```

When I run the test I get the following error:

```
  ● Test suite failed to run

    TypeError: Cannot read property 'onDestroy' of undefined

      24 |   ]
      25 | })
    > 26 | export class CreditInvoiceDetailsComponent implements OnInit, ControlValueAccessor {
         |                                           ^
      27 |   @Output() detailsValid = new EventEmitter<boolean>();
      28 | 
      29 |   constructor(private readonly fb: FormBuilder) {}

      at decorateDirective (../../../node_modules/@ngneat/until-destroy/bundles/ng:/@ngneat/until-destroy/lib/until-destroy.ts:69:52)
      at ../../../node_modules/@ngneat/until-destroy/bundles/ng:/@ngneat/until-destroy/lib/until-destroy.ts:78:7
      at Object.__decorate (../../../node_modules/tslib/tslib.js:95:99)
      at Object.<anonymous> (src/lib/components/credit-invoice-details/credit-invoice-details.component.ts:26:43)
      at Object.<anonymous> (src/lib/components/credit-invoice-details/credit-invoice-details.component.spec.ts:3:1)
```

**Comment by arturovt** [comment] 2020-04-16 08:22
Please, refer to Angular Ivy documentation and provide a _minimal reproducible example_. I will re-open if it's provided, we had been having a lot of [similar issues](https://github.com/ngneat/until-destroy/issues?q=is%3Aissue+TypeError%3A+Cannot+read+property+%27onDestroy%27+is%3Aclosed), there were all resolved by running _ngcc_.

**Closed by arturovt** 2020-04-16 08:22 UTC

**Comment by tanepiper** [comment] 2020-04-16 08:40
@arturovt Yes it seems `ngcc` works, the default one in `nx` has some additional parts to the command it seems that doesn't work well with this:

`"postinstall": "ngcc --properties es2015 browser module main --first-only --create-ivy-entry-points"`

**Comment by arturovt** [comment] 2020-04-16 08:54
Yep. Jest uses UMD bundles because it deals with the CommonJS module system. `--properties es2015 browser module main --first-only` means that _ngcc_ will compile the first target it meats, in that case, you have only _es2015 ngcc_ compiled bundles.

**Comment by cryptobrains** [comment] 2021-02-03 14:54
I've traced the bug in one scenario. If you decorate a regular class (not a component) with @UntilDestroyed() (which used to work fine) then this call in decorateDeclarable(type, options)

        def.onDestroy = decorateNgOnDestroy(def.onDestroy, options);
        
 gets triggered.  It may be that the old behaviour functioning was an illusion. Possibilities: maybe put an assert there that says only components can be decorated, or check for the existence of onDestroy on def before calling it and console.log a statement to the effect that non-components cannot be usefully decorated that way ?
