### ISSUE TITLE
Doesn't work on Angular 9

### ISSUE THREAD

**Issue by ystolyarchuk** [ngneat/until-destroy#55] opened 2020-02-17 11:05 UTC
Unsubscribe doesn't work on Angular 9 but works on correct Angular 8

**Comment by NetanelBasal** [comment] 2020-02-17 11:06
Duplicate of #52

**Comment by ystolyarchuk** [comment] 2020-02-17 11:28
@NetanelBasal I am using ngx-take-until-destroy, and it doesn't work yet

**Comment by arturovt** [comment] 2020-02-17 11:34
Are you able to create a _minimal reproducible example_ for us?

**Comment by NetanelBasal** [comment] 2020-02-17 12:25
@ystolyarchuk read the README before you open an issue. Thanks.

**Closed by NetanelBasal** 2020-02-17 12:25 UTC
