### ISSUE TITLE
 NG0204: Token InjectionToken X is missing a ɵprov definition after Angular 15 upgrade

### ISSUE THREAD

**Issue by akoreh** [ngneat/until-destroy#218] opened 2022-11-29 08:15 UTC
After updating to Angular 15, components with the following setup fail with `NG0204: Token InjectionToken X is missing a ɵprov definition.
`
```
import {
  ChangeDetectionStrategy,
  Component,
  InjectionToken,
  Input,
} from '@angular/core';
import { UntilDestroy } from '@ngneat/until-destroy';

export const FAB_ITEM = new InjectionToken<any>('FAB_ITEM');

@UntilDestroy()
@Component({
  selector: 'aw-fab-item',
  templateUrl: 'fab-item.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
  providers: [{ provide: FAB_ITEM, useExisting: FabItemComponent }],
})
export class FabItemComponent {
  @Input() disabled = false;
}
```

The error dissapears and the component works after removing the `UntilDestroy` decorator.

**Comment by arturovt** [comment] 2022-11-29 09:35
Could you please provide a minimal reproducible example?

**Comment by arturovt** [comment] 2022-11-30 15:52
Closing as not reproducible. We have an integration app in this repository which is running with Angular 15.

Feel free to re-open the issue once you're able to provide a reproducible example.

**Comment by anschm** [comment] 2022-12-16 15:50
Got the same issue after migration to angular 15.

**Comment by anschm** [comment] 2022-12-19 11:15
I saw that the repo was upgradet to angular 15. Could we get a new release? Maybe this fix the issue.

**Comment by arturovt** [comment] 2022-12-19 11:45
Well, I could’ve published a new version but I’d want to double check to ensure this is related to a new version. Because that might be an unnecessary publish. I need a reproducible example gentlemen.

**Comment by anschm** [comment] 2022-12-19 14:54
Could you publish a dev version so that I can check against my project?

**Comment by NetanelBasal** [comment] 2022-12-21 06:56
I'm using Angular v15, and I don't have an issue. It'll be helpful if you can reproduce it.

**Comment by jogelin** [comment] 2022-12-21 08:52
I have had something similar since the upgrade to Angular 15.

We have a use case where we want to get a `MatFormFieldControl` from a `ControlValueAccessor` component implementing the `MatFormFieldControl` that is injected using the Content Projection. 

```typescript
  @ContentChild(MatFormFieldControl, { static: true })
  private formFieldControl!: MatFormFieldControl<unknown>;

  ngOnInit(): void {
    this.matFormField._control = this.formFieldControl;
```

For `MatFormFieldControl` components that have the `UntilDestroy()` decorator, the `this.formFieldControl` is empty
When you remove the decorator, it works well again.

I'll try to provide a reproducible case today

**Comment by jogelin** [comment] 2022-12-22 08:30
I was not able to reproduce our issue on a clean project TBH.

We are still investigating why it is failing by removing all codes around. 

Even if I remove the code within the decorator it is failing. 

Just the fact that we set the decorator has an impact on our `@ContentChild` reaction.

I think this is related to https://github.com/angular/angular/issues/48276 but no idea what is the reason.

**Comment by jogelin** [comment] 2022-12-22 09:50
Even trying that approach it fails:

```
function UntilDestroy(options = {}) {
  return (type: unknown) => {};
}

@UntilDestroy()
@Component({
...
```

So at least, this is not related to this library ;)

**Comment by arturovt** [comment] 2022-12-22 10:11
To be honest I have issues in other libraries as well related to decorators. But it’s usually not a library issue but something related to the application.

Since I’ve seen already some issues related to decorators this means there actually has been some change in the TS compiler or Angular compiler that might affect it.

**Comment by maartencardinaels** [comment] 2022-12-22 10:40
this [typescript issue](https://github.com/microsoft/TypeScript/issues/48814) seems to be related

**Comment by arturovt** [comment] 2022-12-22 16:59
Yeah, I haven't got my hands yet to going through the Angular 15 release completely. In other libraries this is being solved by playing around with `useDefineForClassFields`.

**Comment by arturovt** [comment] 2022-12-27 18:38
Have to re-open the issue because I also experience it in one of my apps (haven't met it earlier):
```
Error: NG0204: Token InjectionToken NgValueAccessor is missing a ɵprov definition.
```

**Comment by arturovt** [comment] 2022-12-27 18:50
@jogelin I have experienced this issue with a control value accessor too. I have fixed it with the `forwardRef`.

Before:
```ts
provide: NG_VALUE_ACCESSOR,
useExisting: CosAutocompleteComponent
```

After:
```ts
provide: NG_VALUE_ACCESSOR,
useExisting: forwardRef(() => CosAutocompleteComponent),
```

Your thoughts?

P.S. I know it wasn't necessary to use `forwardRef` since Ivy has been released (because component definition appeared after the class itself, thus there has been no reason to "capture" the class reference).

**Comment by arturovt** [comment] 2022-12-29 19:47
Ok, I just doubled checked my app and the issue wasn’t related to this library. Sorry for pinging anyone who’s subscribed to this issue.

**Closed by arturovt** 2022-12-29 19:47 UTC

**Comment by jogelin** [comment] 2023-01-04 13:41
> @jogelin I have experienced this issue with a control value accessor too. I have fixed it with the `forwardRef`.
> 
> Before:
> 
> ```ts
> provide: NG_VALUE_ACCESSOR,
> useExisting: CosAutocompleteComponent
> ```
> 
> After:
> 
> ```ts
> provide: NG_VALUE_ACCESSOR,
> useExisting: forwardRef(() => CosAutocompleteComponent),
> ```
> 
> Your thoughts?
> 
> P.S. I know it wasn't necessary to use `forwardRef` since Ivy has been released (because component definition appeared after the class itself, thus there has been no reason to "capture" the class reference).

Seems to work too :)
