### ISSUE TITLE
Abtract component and UntilDestroy decorator

### ISSUE THREAD

**Issue by rivoalrivoal** [ngneat/until-destroy#97] opened 2020-05-22 11:10 UTC
I have the same issue as [Issue 50](https://github.com/ngneat/until-destroy/issues/50)

I use Angular 9 and the error is
`Cannot read property 'onDestroy' of undefined`

**Comment by arturovt** [comment] 2020-05-22 12:48
Provide a _minimal reproducible example_ or see other closed issues.

**Comment by rivoalrivoal** [comment] 2020-05-22 12:56
OK :)

> would like to know if the component decorator @UntilDestroy() is inherited by a class that extends the AbstraceBaseComponent below:
> 
> ```
> @UntilDestroy( { checkProperties: true } )
> @Component(
>   {
>     selector: 'pim-abstract',
>     template: ``
>   } )
> export abstract class AbstractBaseComponent {
>   @Input() maxChars: number
>   currentIndex = -1
> 
> }
> ```
> 
> Is the @UntilDestroy() inherited by the ExtendedClass below?
> 
> ```
> export ExtendedClass extends AbstractBaseComponent {
> 
> }
> ```

**Comment by arturovt** [comment] 2020-05-22 13:16
Reproducible examples should be shared via GitHub.

**Comment by rivoalrivoal** [comment] 2020-05-24 15:33
@arturovt 
Here a sample project
https://github.com/rivoalrivoal/angular-abstract-component-until-destroy

**Comment by arturovt** [comment] 2020-05-24 15:59
That is a good approach :+1: 

I will have a look this evening and will re-open this issue _if it really exists_.

**Comment by arturovt** [comment] 2020-05-24 17:03
I was able to reproduce it. The decorator should not be applied to an abstract class in this case as it's not extended. It cannot be extended by these reasons:
* _AbstractComponent_ is not a component (even if it has _Component_ suffix)
* _untilDestroyed_ creates _Subject_ under the hood on the _instance_ and destroyed with this instance and when you do `super.ngOnInit()` you actually do `AbstractComponent.prototype.ngOnInit.call(this)` which calls parent method with `this` of the child component, which means there is no `Subject`.

P.S. I'm just explaining the process and not saying that this's the wrong or right approach.

Let's re-open this issue for further discussion.

I'm just thinking if we've got 2 declarables:
* ```ts
  @UntilDestroy()
  @Directive()
  export abstract class ParentDirective { ... }
  ```

* ```ts
  @Component({ template: '' })
  export class ChildComponent extends ParentDirective {
    constructor() { of().pipe(untilDestroyed(this)).subscribe() }
  }
  ```

1) They, of course, will have different directive/component definitions.
2) `ParentDirective` `def.onDestroy` will be overridden by `UntilDestroy` decorator
3) It will be called with `onDestroy.call(childComponentInstance)` thus it will be able to complete the `Subject` on the `ChildComponent`

So the problem is only in `missingDecorator` function which checks if the `UntilDestroy` decorator is applied. It checks only `ChildComponent.def[decoratorApplied] === true` but doesn't go forward through the prototype chain.

@NetanelBasal as I understand we need to add some mechanism that will traverse the prototype chain and check parent component/directive definitions, wtyd?

**Comment by NetanelBasal** [comment] 2020-05-25 07:03
Yes, make sense.

**Comment by maxtacco** [comment] 2020-05-27 13:39
This actually prevents us from fully migrating to Angular 9 because we have a lot of abstract base component classes. Does ngx-take-until-destroy work with Angular 9?

**Comment by maxtacco** [comment] 2020-06-04 14:35
Hi @arturovt, I know it is an open source project and you have your own priorities but do you have any idea when someone would be able to take a look at this issue (days, weeks, months)? The way things are right now there is no parity between @ng-neat/until destroy and ngx-take-unti-destroy functionality and you really should mention this in the migration docs so that others are aware of possible issues.

**Comment by NetanelBasal** [comment] 2020-07-06 15:03
We currently busy. You're welcome to submit a PR.

**Comment by arturovt** [comment] 2020-07-27 19:58
`@ngneat/until-destroy@8.0.0` has been published. Could you give it a try?

**Comment by arturovt** [comment] 2020-08-17 08:52
Can this be closed?

**Comment by arturovt** [comment] 2020-08-19 19:10
Closing as fixed. Feel free to open an issue if the problem persists.

**Closed by arturovt** 2020-08-19 19:10 UTC
Labels: priority: medium, type: bug/fix
