### ISSUE TITLE
How to declare and use with ionic 3 pages

### ISSUE THREAD

**Issue by mapicard** [ngneat/until-destroy#57] opened 2020-02-19 02:02 UTC
I installed the package in my project with 
`  "npm install @ngneat/until-destroy"`
I declared in my page
`import { UntilDestroy, untilDestroyed } from '@ngneat/until-destroy';`
`@UntilDestroy()`
`export class myClass {`
`...`
  `  constructor(pServer: Servers) { `
`        this.pServers.getServers().pipe(untilDestroyed(this)).subscribe((servers) => { `
`...`

And then when I build I get these errors

`Typescript Error`
`'=' expected. `
` node_modules/@ngneat/until-destroy/lib/internals.d.ts `
`export declare const DESTROY: unique symbol; `
`export declare function markAsDecorated(providerOrDef: InjectableType<unknown> | DirectiveDef<unknown> | ComponentDef<unknown>): void; `

**Comment by arturovt** [comment] 2020-02-28 23:25
Could you create a _minimal reproducible example_?

**Comment by mapicard** [comment] 2020-02-29 15:28
I made a minimal setup (https://i3-provider-untildestroy.stackblitz.io) but i'm getting another issue.
`Cannot read property 'onDestroy' of undefined`

**Comment by DmitryEfimenko** [comment] 2020-03-03 09:03
it seems there's the same issue with Ionic 4

**Comment by NetanelBasal** [comment] 2020-03-03 09:07
@mapicard you should enable Ivy

**Comment by mapicard** [comment] 2020-03-03 15:51
Ok, I'm not familiar with this and willing to give it a try but can you elaborate a bit on how it could fix the issue? I am using Ionic3 with Angular5.

**Comment by arturovt** [comment] 2020-03-03 17:24
@mapicard 

:D

It requires Angular 9+.

**Comment by mapicard** [comment] 2020-03-03 17:34
What requires Angular9+ `ngneat/until-destroy,` Ivy, or both?

**Comment by arturovt** [comment] 2020-03-09 14:53
@mapicard both.

**Comment by DmitryEfimenko** [comment] 2020-03-09 21:37
these two words answers are really confusing.
I have an app using Ionic 4, Angular 8 (Ivy disabled). I get an error in either case - whether the Decorator is used or not. Does this mean that this library won't work without Ivy enabled?

**Comment by arturovt** [comment] 2020-03-09 21:54
@DmitryEfimenko 

Why? Have you read the readme? :wink:  I guess there is no sense of copy-pasting it here :D

**Comment by DmitryEfimenko** [comment] 2020-03-09 23:05
I did, but your comment made me look at it again. I remember seeing that under [Use with View Engine](https://github.com/ngneat/until-destroy#use-with-view-engine) section the import was from a different package: `ngx-take-until-destroy`. I assumed that it was a typo and kept trying using the `@ngneat/until-destroy`. Now I understand that's intentional. Thanks!

**Comment by DmitryEfimenko** [comment] 2020-03-09 23:08
I'm wondering if this confusion could be mitigated by bringing the ViewEngine functionality into this package. The import would look something like:
```ts
import { untilDestroyed } from @ngneat/until-destroy/view-engine
```
Or is that an overkill that does not help anything?

**Comment by bleuscyther** [comment] 2020-03-17 10:13
Same one Ionic 5 it never used `onDestroy `but `ionViewDidLeave `

**Comment by arturovt** [comment] 2020-03-31 19:37
Gentlemen, it's been 2 months and seems like no one hasn't provided any _minimal reproducible example_. :(

**Comment by DmitryEfimenko** [comment] 2020-04-01 17:21
I didn't feel there's a need for it since (with your help) I figured out what the issue was. I'd say the whole thing boils down to the confusion that ViewEngine requires a use of a different package. I think other people are just confused about it. If that's not the case, then yeah, repro is still required.

**Comment by bleuscyther** [comment] 2020-04-04 12:15
@arturovt I was using the wrong package with angular 9. 
fixed it 
angular 9  (Ivy) :  **@ngneat/until-destroy**
angular 8 ( no-ivy) & bellow  :  **ngx-take-until-destroy**

Everything works well now 🎉. I was reading the comments out of context, based on te old documentation for the library.

Just a additional note for anyone else using IonicFramework and OnDestroy 

- [Ionic Angular lifecycle](https://ionicframework.com/docs/angular/lifecycle)
- [StackOverflow: Ionic Components are not destroyed after navigation to another page ](https://stackoverflow.com/questions/52539823/ionic-components-are-not-destroyed-after-navigation-to-another-page/55291105#55291105);

@mapicard Ionic 3 is not using Ivy,. The last version of Angular i used with it was angular 7. The changed the events after that . ([Migrating from Ionic 3.0 to Ionic 4.0](https://ionicframework.com/docs/reference/migration#migrating-from-ionic-3-0-to-ionic-4-0)).
You can use the old documentation and it will work :
[ Use with View Engine (Pre Ivy) ](https://github.com/ngneat/until-destroy#use-with-view-engine-pre-ivy)

**Comment by NetanelBasal** [comment] 2020-04-04 17:37
Thanks, closing this issue.

**Closed by NetanelBasal** 2020-04-04 17:37 UTC

**Comment by arturovt** [comment] 2020-04-04 18:08
@bleuscyther thanks for providing this information!
